@echo off
FOR /f %%p in ('where python') do SET PYTHONPATH=%%p
echo Checking requirements...
python -m pip install -r requirements.txt
echo Starting the bot (this may take a minute or two)...
python loopself.py